apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  labels:
    app: consumer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-app
          image: sowmyaa7501/consumer_app:4.0
          imagePullPolicy: Always